# Question 1

In [3]:
import numpy as np
arr=np.zeros(10)
arr[4]=1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Question 2

In [4]:
a1=np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Question 3

In [5]:
m1=np.arange(9).reshape(3,3)
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Question 4

In [7]:
m1=np.nonzero([1,2,0,0,4,0])
print(m1)

(array([0, 1, 4], dtype=int64),)


# Question 5

In [13]:
m1=np.random.randint((10,10))
a,b=m1.min(),m1.max()
print("minimun is",a,"maximum is",b)

minimun is 8 maximum is 9


# Question 6

In [19]:
p=np.random.random(30)
m=p.mean()
print("mean is",m)

mean is 0.5425563605790292
